spring:
  application:
    name: SpringDemo
#  config:
#    import:
#      - "classpath:logging-config.yml"
#      - "classpath:port-config.yml"

management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

server.port: 8080
